-- AlterTable: campos Law Sovereign v3.5
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "chanceOfSuccess" INTEGER;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "costOfWaiting" DOUBLE PRECISION;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "missingProofs" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "isPaperLead" BOOLEAN NOT NULL DEFAULT false;
